# General #####################################################################
# element_list: 

degree: 2

output_directory: "./output"

verbose: 2

random_seed: 1234

progress_bars: True

# Preprocess ##################################################################
experiment_path: "./data/"

filename_pattern: "vasprun*"

cache_data: True

data_filename: "data.db"

max_samples_per_file: -1

min_diff: 0.0

analyze_pair_distribution: True

analyze_fraction: 1.0

vasp_pressure: False

# Featurization ###############################################################
read_knots: False

write_knots: True

knots_file: "knots.json"

# r_min_map:

# r_max_map:

# resolution_map:

n_jobs: 2

parallel: "python"

cache_features: True

features_filename: "features.db"

knot_spacing: "linear"


# Learning ####################################################################
frac_train: 0.5

kappa: 0.99  # 1.0 to disable force-training

regularization_params:
    ridge_1b: 1.0e-4
    ridge_2b: 1.0e-9
    ridge_3b: 1.0e-6
    curve_2b: 1.0e-9
    curve_3b: 1.0e-6
    
zero_tail: True

fit_self_energy: True
    
cache_features: True

features_filename: "features.db"

model_filename: "model.json"

training_filename: "training.txt"

# Postprocess #################################################################
core_correction: 1.1

plot_fit: True

plot_2B: True

plot_3B: True






